---
# tasks file for aws-vault | Debian/Ubuntu Family

- name: Debian/Ubuntu Family | Downloading archive for {{ awsvault_app }} {{ awsvault_version }} to {{ awsvault_bin_path }}
  get_url:
    url: "{{ awsvault_dl_url }}"
    dest: "{{ awsvault_bin_path }}/{{ awsvault_app }}"
    owner: "{{ awsvault_file_owner }}"
    group: "{{ awsvault_file_group }}"
    mode: "{{ awsvault_file_mode }}"
