---
# tasks file for aws-vault | EL Family

- name: EL Family | Downloading archive for {{ awsvault_app }} {{ awsvault_version }} to {{ awsvault_bin_path }}
  get_url:
    url: "{{ awsvault_dl_url }}"
    dest: "{{ awsvault_bin_path }}/{{ awsvault_app }}"
    mode: "{{ awsvault_file_mode }}"
